### ISSUE TITLE
nanopi neo config

### ISSUE THREAD

**Issue by somuchtyler** [Yura80/pikvm-rock64#1]
What config file would compile for the nanopi neo to generate v2-hdmiusb-generic-arm-nanopi-neo.img.bz2 ?
I only see these four and none of them are for the nanopi neo?
config.mk.libretech-all-h3-cc
config.mk.orangepi-one
config.mk.orangepi-zero
config.mk.rock64

BTW, Amazing work!!

**Comment by Yura80** [comment]
I'll add it later. Meanwhile you may use orangepi one config by changing UBOOT to "nanopi-neo"

**Comment by Yura80** [comment]
I've added more configs
