### ISSUE TITLE
NanoPI Neo: support for onboard USB ports

### ISSUE THREAD

**Issue by chewiebrian** [Yura80/pikvm-rock64#5]
Hi, thanks for your awesome work. I am setting up a PiKVM with a NanoPI Neo 256MB and everything has been very straightfully so far; download your SD image, boot, profit ;)

I am trying to use the onboard USB1 and USB2 ports, using a USB with the classical green terminal block connector (https://www.amazon.com/SamIdea-Terminal-Connector-Screwdriver-terminals/dp/B07SYYX6SV) in order to wire it to the pins on the NanoPI. My plan is to use a USB HID relay to drive the power and reset signal to the PC motherboard. Everything works if I use a USB hub with the external USB A connector, but I dont want to share the port with the HDMI-USB dongle. The internal ports, altough are being detected by the kernel and lsusb, dont detect anything when plugged. The HID relays lights up but the dmesg trace/lsusb shows nothing.

Is there any way for using those internal USB ports?

Thanks again and greetings from Spain ;)

**Comment by HotelMoted** [comment]
Give this thing a read
https://forum.armbian.com/topic/5256-edit-neo2-only-2-usb-ports-working-female-a-and-usb2-pin-header/
https://stackoverflow.com/questions/63256595/enable-usb-on-nanopi-neo
Sounds like the internal USB ports are default left disabled, you are going to have to modify the DTB/DTS file and recompile.

# Convert binary to text
dtc -I dtb /boot/dtb/sun8i-h3-nanopi-neo.dtb -O dts -o /boot/dtb/sun8i-h3-nanopi-neo.dts

[...edit .dts file here...]

# Convert text to binary
dtc -I dts /boot/dtb/sun8i-h3-nanopi-neo.dts -O dtb -o /boot/dtb/sun8i-h3-nanopi-neo.dtb


(make sure you back up the initial "/boot/dtb/sun8i-h3-nanopi-neo.dtb" file)

**Comment by HotelMoted** [comment]
If it were me I would just install armbian temporarily and then use https://forum.armbian.com/topic/6191-usb-on-nanopi-neo-air-with-mainline-kernel/ the armbian config tool to enable the usb ports, then I would steal the DTB file from that install and put it on the pikvm.

**Comment by chewiebrian** [comment]
But aren't the DTB files kernel-dependant? Would they work with your arch-based image?

**Comment by HotelMoted** [comment]
AFAIK you can convert DTB to DTS and then DTS to DTB on any machine you want... Worst case scenario you could convert your DTB file to DTS and then the one you get from armbian to DTS and run a diff on it, then just transfer the changes on your archlinux pikvm and convert back to DTB.

This is the file on the archlinux pikvm: /boot/dtbs/sun8i-h3-nanopi-neo.dtb
I am not sure the location of the dtb file on the armbian install though.

Also once you get it working come back and let me know if it worked, because I am considering on enabling my ports on my nanopi neo pikvm was well

**Comment by HotelMoted** [comment]
try this:
# rw
# cp /boot/dtbs/sun8i-h3-nanopi-neo.dtb ~/backup.dtb
# pacman -Sy
# pacman -S dtc
# dtc -I dtb ~/backup.dtb -O dts -o ~/backup.dts
# nano -w ~/backup.dts
Control-W (find) "1c1b000" change from status: "disabled" to status: "okay"
Control-W (find) "1c1b400" change from status: "disabled" to status: "okay"
Control-W (find) "1c1c000" change from status: "disabled" to status: "okay"
Control-W (find) "1c1c400" change from status: "disabled" to status: "okay"
Control-X (y to confirm)
# dtc -I dts ~/backup.dts -O dtb -o ~/new.dtb
(this generates a bunch of warnings that seem to be fine)
# cp ~/new.dtb /boot/dtbs/sun8i-h3-nanopi-neo.dtb
# reboot

                ehci0 = "/soc/usb@1c1a000"; <- this one is already enabled (DM0 aka OTG/Power Port ?)
                ohci0 = "/soc/usb@1c1a400"; <- this one is already enabled (DM0 aka OTG/Power Port ?)
                ehci1 = "/soc/usb@1c1b000"; <- change this one from "disabled" to "okay" (DM1 Port ?)
                ohci1 = "/soc/usb@1c1b400"; <- change this one from "disabled" to "okay" (DM1 Port ?)
                ehci2 = "/soc/usb@1c1c000"; <- change this one from "disabled" to "okay" (DM2 Port ?)
                ohci2 = "/soc/usb@1c1c400"; <- change this one from "disabled" to "okay" (DM2 Port ?)
                ehci3 = "/soc/usb@1c1d000"; <- this one is already enabled (DM3 aka Host Type-A Port ?)
                ohci3 = "/soc/usb@1c1d400"; <- this one is already enabled (DM3 aka Host Type-A Port ?)

I did this and it didn't seem to break anything

**Comment by chewiebrian** [comment]
Wow, worked like a charm! Now the relay works from pikvm. Here is a photo of my setup:

![IMG_20210514_215145](https://user-images.githubusercontent.com/873178/118322398-57585900-b4ff-11eb-89a9-a3d49da1ae82.jpg)

Thanks a lot!
